"use client";

/**
 * Central premium icon language for Vytal — built on Phosphor Icons.
 *
 * Why centralized: swapping the platform's icon set later means editing this one
 * file, not 80 components. New / revamped surfaces import their icons from here so
 * the whole product speaks one visual language (consistent weight + metaphors).
 */

import {
  House,
  Gauge,
  Heartbeat,
  Wallet,
  CalendarBlank,
  BookmarkSimple,
  ArrowsLeftRight,
  FileText,
  GearSix,
  MagnifyingGlass,
  ChartBar,
  ChartLineUp,
  ChartPieSlice,
  ChatCircleDots,
  Bell,
  Sparkle,
  Trash,
  Lightning,
  TrendUp,
  TrendDown,
  Pulse,
  ShieldCheck,
  Brain,
  Target,
  Coins,
  Buildings,
  Newspaper,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  CaretRight,
  CaretDown,
  CaretUp,
  Plus,
  X,
  Check,
  Star,
  Record as RecordIcon,
  Eye,
  Clock,
  Fire,
  Crown,
  Compass,
  Stack,
  Funnel,
  DotsThree,
  Command,
  List,
  SignOut,
  User,
  Question,
  Info,
  WarningCircle,
  CheckCircle,
  ArrowCounterClockwise,
  ArrowsOutSimple,
  ArrowsInSimple,
  SidebarSimple,
  Scales,
  Rocket,
  Graph,
  CircleNotch,
  EyeSlash,
  EnvelopeSimple,
  LockKey,
  Pause,
  Play,
  PencilSimple,
  // ── data-admin surfaces (ingestion pipelines) ──
  Warning,
  ShieldWarning,
  Prohibit,
  Cpu,
  Database,
  DownloadSimple,
  CloudArrowDown,
  Globe,
  Hash,
  ClockCounterClockwise,
  Package,
  RssSimple,
  PaperPlaneTilt,
  SkipForward,
  Timer,
  UserFocus,
  Wrench,
  XCircle,
  type Icon,
  type IconWeight,
} from "@phosphor-icons/react";

export type { Icon, IconWeight };

/* Navigation + product surface icons (semantic names → premium glyphs) */
export const Icons = {
  dashboard: Gauge,
  health: Heartbeat,
  portfolio: Wallet,
  calendar: CalendarBlank,
  watchlist: BookmarkSimple,
  compare: ArrowsLeftRight,
  results: FileText,
  settings: GearSix,
  screener: MagnifyingGlass,
  sector: ChartPieSlice,
  home: House,

  // signals
  trendUp: TrendUp,
  trendDown: TrendDown,
  pulse: Pulse,
  shield: ShieldCheck,
  brain: Brain,
  target: Target,
  spark: Sparkle,
  chat: ChatCircleDots,
  bolt: Lightning,
  fire: Fire,
  crown: Crown,
  scales: Scales,
  rocket: Rocket,
  graph: Graph,
  chartBar: ChartBar,
  chartLine: ChartLineUp,
  coins: Coins,
  building: Buildings,
  news: Newspaper,
  compass: Compass,
  stack: Stack,

  // controls / chrome
  bell: Bell,
  search: MagnifyingGlass,
  filter: Funnel,
  more: DotsThree,
  command: Command,
  menu: List,
  signout: SignOut,
  user: User,
  eye: Eye,
  eyeSlash: EyeSlash,
  pause: Pause,
  play: Play,
  edit: PencilSimple,
  trash: Trash,
  clock: Clock,
  spinner: CircleNotch,
  envelope: EnvelopeSimple,
  lock: LockKey,
  star: Star,
  // A neutral ring-with-centre-dot marker ("a reading exists here") — the Family-N (Notable)
  // family glyph. Phosphor has no literal "circle-dot"; Record IS that glyph (fill weight = ring
  // + filled centre dot). Deliberately NOT star/check/award/heart/arrow — no approval, rating, or
  // direction coding on a constructive finding (Family N Amendment §8.1).
  circleDot: RecordIcon,
  plus: Plus,
  close: X,
  check: Check,
  info: Info,
  question: Question,
  warning: WarningCircle,
  warningTriangle: Warning,
  shieldWarning: ShieldWarning,
  prohibit: Prohibit,
  xCircle: XCircle,
  success: CheckCircle,
  refresh: ArrowCounterClockwise,

  // data-admin surfaces (ingestion pipelines)
  cpu: Cpu,
  database: Database,
  download: DownloadSimple,
  downloadCloud: CloudArrowDown,
  globe: Globe,
  hash: Hash,
  history: ClockCounterClockwise,
  package: Package,
  rss: RssSimple,
  send: PaperPlaneTilt,
  skipForward: SkipForward,
  timer: Timer,
  userFocus: UserFocus,
  wrench: Wrench,

  // arrows / carets
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  caretRight: CaretRight,
  caretDown: CaretDown,
  caretUp: CaretUp,
  arrowsOutSimple: ArrowsOutSimple,
  arrowsInSimple: ArrowsInSimple,
  /** The show/hide-a-side-panel toggle — one glyph for both directions, the way the app sidebar's own
   *  trigger works. Used by /chat's conversation rail. */
  sidebarSimple: SidebarSimple,
} satisfies Record<string, Icon>;

export type IconName = keyof typeof Icons;
