"use client";

/**
 * Central premium icon language for InvestIQ — built on Phosphor Icons.
 *
 * Why centralized: swapping the platform's icon set later means editing this one
 * file, not 80 components. New / revamped surfaces import their icons from here so
 * the whole product speaks one visual language (consistent weight + metaphors).
 */

import {
  House,
  Gauge,
  Heartbeat,
  Wallet,
  CalendarBlank,
  BookmarkSimple,
  ArrowsLeftRight,
  FileText,
  GearSix,
  MagnifyingGlass,
  ChartBar,
  ChartLineUp,
  ChartPieSlice,
  Bell,
  Sparkle,
  Lightning,
  TrendUp,
  TrendDown,
  Pulse,
  ShieldCheck,
  Brain,
  Target,
  Coins,
  Buildings,
  Newspaper,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  CaretRight,
  CaretDown,
  CaretUp,
  Plus,
  X,
  Check,
  Star,
  Eye,
  Clock,
  Fire,
  Crown,
  Compass,
  Stack,
  Funnel,
  DotsThree,
  Command,
  List,
  SignOut,
  User,
  Question,
  Info,
  WarningCircle,
  CheckCircle,
  ArrowCounterClockwise,
  Scales,
  Rocket,
  Graph,
  type Icon,
  type IconWeight,
} from "@phosphor-icons/react";

export type { Icon, IconWeight };

/* Navigation + product surface icons (semantic names → premium glyphs) */
export const Icons = {
  dashboard: Gauge,
  health: Heartbeat,
  portfolio: Wallet,
  calendar: CalendarBlank,
  watchlist: BookmarkSimple,
  compare: ArrowsLeftRight,
  results: FileText,
  settings: GearSix,
  screener: MagnifyingGlass,
  sector: ChartPieSlice,
  home: House,

  // signals
  trendUp: TrendUp,
  trendDown: TrendDown,
  pulse: Pulse,
  shield: ShieldCheck,
  brain: Brain,
  target: Target,
  spark: Sparkle,
  bolt: Lightning,
  fire: Fire,
  crown: Crown,
  scales: Scales,
  rocket: Rocket,
  graph: Graph,
  chartBar: ChartBar,
  chartLine: ChartLineUp,
  coins: Coins,
  building: Buildings,
  news: Newspaper,
  compass: Compass,
  stack: Stack,

  // controls / chrome
  bell: Bell,
  search: MagnifyingGlass,
  filter: Funnel,
  more: DotsThree,
  command: Command,
  menu: List,
  signout: SignOut,
  user: User,
  eye: Eye,
  clock: Clock,
  star: Star,
  plus: Plus,
  close: X,
  check: Check,
  info: Info,
  question: Question,
  warning: WarningCircle,
  success: CheckCircle,
  refresh: ArrowCounterClockwise,

  // arrows / carets
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  caretRight: CaretRight,
  caretDown: CaretDown,
  caretUp: CaretUp,
} satisfies Record<string, Icon>;

export type IconName = keyof typeof Icons;
